#!/bin/bash

#numero=$1

qs -n -g -s streamcloud $1 $2 $3 $4 $5 $6 $7 $8 $9 > qsout
qs -n -g -s streamcloud $1 $2 $3 $4 $5 $6 $7 $8 $9 >> qsout
qs -n -g -s streamcloud $1 $2 $3 $4 $5 $6 $7 $8 $9 >> qsout
qs -n -g -s streamcloud $1 $2 $3 $4 $5 $6 $7 $8 $9 >> qsout

DATOS=`grep 'http://' qsout`
readarray enlaces <<< "$DATOS"
for enlace in "${enlaces[@]}"; do
	firefox "$enlace"
done